version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 2s
      retries: 3
#      start_period: 30s
#      start_interval: 10s
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - db_network
    volumes:
      - ./squema.sql:/docker-entrypoint-initdb.d/a.sql # Montar el script SQL en el contenedor de inicialización

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - db_network

  python-app:
    build: ./turtle_inc
    image: app:latest
    container_name: app
    restart: always
    command: sh -c "python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./turtle_inc:/src
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - db_network

networks:
  db_network:
