# Generated by Django 4.2.5 on 2023-10-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nro_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'e01_cliente',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'e01_producto',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nro_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_sin_iva', models.FloatField()),
                ('iva', models.FloatField()),
                ('total_con_iva', models.FloatField(blank=True, null=True)),
                ('nro_cliente', models.ForeignKey(db_column='nro_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.cliente')),
            ],
            options={
                'db_table': 'e01_factura',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_area', models.IntegerField()),
                ('nro_telefono', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('nro_cliente', models.ForeignKey(db_column='nro_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='api.cliente')),
            ],
            options={
                'db_table': 'e01_telefono',
                'unique_together': {('codigo_area', 'nro_telefono')},
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_item', models.IntegerField()),
                ('cantidad', models.FloatField()),
                ('codigo_producto', models.ForeignKey(db_column='codigo_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='api.producto')),
                ('nro_factura', models.ForeignKey(db_column='nro_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='api.factura')),
            ],
            options={
                'db_table': 'e01_detalle_factura',
                'unique_together': {('nro_factura', 'codigo_producto')},
            },
        ),
    ]
